// Generates dist/sw.js after `astro build`, precaching every page and asset
// so the whole songbook (lyrics, chords, tabs) works fully offline.
//
// Astro's static build renders HTML outside Vite's normal client-bundle
// lifecycle, so tools like vite-plugin-pwa/workbox (which hook into that
// lifecycle to generate the service worker) never fire here — hand-rolling
// a small one against the actual `dist` output sidesteps that entirely.
//
// Usage: runs automatically via `npm run build` (see package.json postbuild)

import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const DIST_DIR = fileURLToPath(new URL('../dist', import.meta.url));
const BASE = '/offthemap/';

// Large, non-essential download — skip precaching it so install stays fast;
// it's still cached opportunistically the first time someone opens it.
const EXCLUDE = new Set(['lyrics.pdf']);

async function collectFiles(dir, prefix = '') {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const relPath = path.posix.join(prefix, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await collectFiles(path.join(dir, entry.name), relPath)));
    } else if (!EXCLUDE.has(relPath)) {
      files.push(relPath);
    }
  }
  return files;
}

// Every route is served directory-style (e.g. `/songbook/foo/`, resolved by
// the static host to `songbook/foo/index.html`) — that's how every internal
// link in this site is built, so the service worker precaches under the
// same URLs the browser actually requests, not the raw file paths.
function toRequestUrl(relPath) {
  if (relPath === 'index.html') return BASE;
  if (relPath.endsWith('/index.html')) return BASE + relPath.slice(0, -'index.html'.length);
  return BASE + relPath;
}

const files = await collectFiles(DIST_DIR);
const urls = files.map(toRequestUrl);

// A content hash keeps the cache name stable across no-op builds, so
// returning visitors don't redownload everything on every deploy.
const hash = createHash('sha256');
for (const file of [...files].sort()) {
  hash.update(file);
  hash.update(await readFile(path.join(DIST_DIR, file)));
}
const CACHE_NAME = `off-the-map-${hash.digest('hex').slice(0, 10)}`;

const sw = `// Generated by scripts/generate-sw.mjs — do not edit by hand.
const CACHE_NAME = ${JSON.stringify(CACHE_NAME)};
const PRECACHE_URLS = ${JSON.stringify(urls)};
const OFFLINE_FALLBACK = ${JSON.stringify(BASE)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE_NAME)
      .then((cache) => cache.addAll(PRECACHE_URLS))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;

  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return;

  event.respondWith(
    caches.match(event.request).then((cached) => {
      if (cached) return cached;

      return fetch(event.request)
        .then((response) => {
          if (response.ok) {
            const copy = response.clone();
            caches.open(CACHE_NAME).then((cache) => cache.put(event.request, copy));
          }
          return response;
        })
        .catch(() => caches.match(OFFLINE_FALLBACK));
    })
  );
});
`;

await writeFile(path.join(DIST_DIR, 'sw.js'), sw);
console.log(`Generated dist/sw.js — precaching ${urls.length} files (cache ${CACHE_NAME}).`);
